# Generated by Django 4.2.7 on 2023-11-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextoImagenes',
            new_name='Registro',
        ),
    ]
