# Generated by Django 4.2.7 on 2023-11-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_registro_fecha_alter_registro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='curso',
            field=models.CharField(blank=True, choices=[('1ro de bachillerato', '1ro de bachillerato'), ('2do de bachillerato', '2do de bachillerato'), ('3ro de bachillerato', '3ro de bachillerato'), ('4to de bachillerato', '4to de bachillerato'), ('5to de bachillerato', '5to de bachillerato'), ('6to de bachillerato', '6to de bachillerato')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('Dominicana', 'Dominicana'), ('Haitiana', 'Haitiana'), ('Venezolana', 'Venezolana'), ('Colombiana', 'Colombiana'), ('Peruana', 'Peruana')], default='Dominicana', max_length=100, null=True),
        ),
    ]
